run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - errcheck
    - gofmt
    - goimports
    - gocyclo

linters-settings:
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 40
